version: '3.8'

services:
  task-manager:
    build: .
    ports:
      - '80:80'
    container_name: task-manager-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: task-manager-network
