import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-regions',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './regions.component.html',
  styleUrl: './regions.component.css',
})
export class RegionsComponent {
  title = 'Regiones y Generaciones';

  regions = [
    {
      name: 'Kanto',
      generation: 1,
      pokemonCount: 151,
      emoji: '🏔️',
      description: 'La región original donde comenzó la aventura Pokémon',
      starters: ['Bulbasaur', 'Charmander', 'Squirtle'],
      legendary: ['Articuno', 'Zapdos', 'Moltres', 'Mewtwo', 'Mew'],
    },
    {
      name: 'Johto',
      generation: 2,
      pokemonCount: 100,
      emoji: '🏯',
      description: 'Una región tradicional con fuertes raíces históricas',
      starters: ['Chikorita', 'Cyndaquil', 'Totodile'],
      legendary: ['Raikou', 'Entei', 'Suicune', 'Lugia', 'Ho-Oh', 'Celebi'],
    },
    {
      name: 'Hoenn',
      generation: 3,
      pokemonCount: 135,
      emoji: '🌴',
      description: 'Una región tropical con abundante naturaleza',
      starters: ['Treecko', 'Torchic', 'Mudkip'],
      legendary: [
        'Regirock',
        'Regice',
        'Registeel',
        'Latias',
        'Latios',
        'Kyogre',
        'Groudon',
        'Rayquaza',
        'Jirachi',
        'Deoxys',
      ],
    },
    {
      name: 'Sinnoh',
      generation: 4,
      pokemonCount: 107,
      emoji: '❄️',
      description: 'Una región fría con montañas nevadas',
      starters: ['Turtwig', 'Chimchar', 'Piplup'],
      legendary: [
        'Uxie',
        'Mesprit',
        'Azelf',
        'Dialga',
        'Palkia',
        'Giratina',
        'Heatran',
        'Regigigas',
        'Cresselia',
        'Darkrai',
        'Shaymin',
        'Arceus',
      ],
    },
    {
      name: 'Unova',
      generation: 5,
      pokemonCount: 156,
      emoji: '🏙️',
      description: 'Una región moderna y urbana',
      starters: ['Snivy', 'Tepig', 'Oshawott'],
      legendary: [
        'Victini',
        'Cobalion',
        'Terrakion',
        'Virizion',
        'Tornadus',
        'Thundurus',
        'Reshiram',
        'Zekrom',
        'Landorus',
        'Kyurem',
        'Keldeo',
        'Meloetta',
        'Genesect',
      ],
    },
    {
      name: 'Kalos',
      generation: 6,
      pokemonCount: 72,
      emoji: '🗼',
      description: 'Una región elegante inspirada en Francia',
      starters: ['Chespin', 'Fennekin', 'Froakie'],
      legendary: ['Xerneas', 'Yveltal', 'Zygarde', 'Diancie', 'Hoopa', 'Volcanion'],
    },
    {
      name: 'Alola',
      generation: 7,
      pokemonCount: 81,
      emoji: '🏝️',
      description: 'Un archipiélago tropical con una cultura única',
      starters: ['Rowlet', 'Litten', 'Popplio'],
      legendary: [
        'Tapu Koko',
        'Tapu Lele',
        'Tapu Bulu',
        'Tapu Fini',
        'Cosmog',
        'Cosmoem',
        'Solgaleo',
        'Lunala',
        'Necrozma',
        'Magearna',
        'Marshadow',
        'Poipole',
        'Naganadel',
        'Stakataka',
        'Blacephalon',
        'Zeraora',
        'Meltan',
        'Melmetal',
      ],
    },
    {
      name: 'Galar',
      generation: 8,
      pokemonCount: 89,
      emoji: '🏰',
      description: 'Una región inspirada en Reino Unido',
      starters: ['Grookey', 'Scorbunny', 'Sobble'],
      legendary: [
        'Zacian',
        'Zamazenta',
        'Eternatus',
        'Kubfu',
        'Urshifu',
        'Regieleki',
        'Regidrago',
        'Glastrier',
        'Spectrier',
        'Calyrex',
      ],
    },
  ];

  constructor() {}
}
